### ISSUE TITLE
Test Mode

### ISSUE THREAD

**Issue by LucidityDesign** [DavidGMarquez/Bitadroid#11]
Hi,

I was expecting that a mac address that says `test` starts the test mode which is built into the bitalino firmware. When I set the mac address to `test` I get the following error:

```
[...]
Caused by: java.lang.IllegalArgumentException: test is not a valid Bluetooth address
    at android.bluetooth.BluetoothDevice.<init>(BluetoothDevice.java:852)
[...]
```

Is there a mechanism in this app which starts the test / simulation mode?

**Comment by DavidGMarquez** [comment]
Is the first time that I hear about a test mac address. Sorry but the application is only prepared to work with real mac addresses. 
What is supposed to happen?

**Comment by LucidityDesign** [comment]
This is one line where the test mac address appears:
https://github.com/DavidGMarquez/Bitadroid/blob/master/Bplux/src/ceu/marten/ui/NewConfigurationActivity.java#L504

The bitalino firmware has a test mode where it sends mock data even if you have no sensors connected.

Here is the firmware c-class that implements the test mode: https://github.com/BITalinoWorld/firmware-bitalino/blob/master/simul.c

**Comment by DavidGMarquez** [comment]
That check was only to create configurations easily without a mac to test the interface of the Android version, probably should disappear  in future versions. 

Without a mac you can not connect to the Bitalino with the app. 
Maybe is possible to activate the test mode from Android with the mac address of the device but that is not supported by the app, sorry.

**Comment by LucidityDesign** [comment]
Thanks for your reply.

Can you please give me a hint where the Android app is talking to the Bitalino firmware?

**Comment by DavidGMarquez** [comment]
I think that the class https://github.com/DavidGMarquez/Bitadroid/blob/master/Bplux/src/com/bitalino/deviceandroid/BitalinoAndroidDevice.java as the interface with the Bitalino device.

**Comment by LucidityDesign** [comment]
Thanks.
